python train.py \
    --dataset_path ../../dataset/lora/huanhuan.json \
    --model_path ../../dataset/model \
    --base_model Atom-7B\
    --lora_rank 8 \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --max_steps 120000 \
    --save_steps 40000 \
    --save_total_limit 3 \
    --learning_rate 1e-4 \
    --fp16 \
    --remove_unused_columns false \
    --logging_steps 10 \
    --output_dir ../../output